### ISSUE TITLE
Пакетное распознавание номера

### ISSUE THREAD

**Issue by GR1NE** [bpteam/gd2-php-ocr#2]
https://yadi.sk/d/gqnspcj03EZpb5 - пример файла

**Comment by GR1NE** [comment]
https://yadi.sk/d/DOBeSdUG3EZrgH - 500 файлов изображений

**Comment by bpteam** [comment]
Для начала работы нужно сформировать шаблон при помощи генератора ./template_generator/generator.php

После сохранения шаблона нужно его сохранить в файл и потом подключить при распозновании.
