### ISSUE TITLE
There is no file "bootstrap.php"

### ISSUE THREAD

**Issue by mav1** [bpteam/gd2-php-ocr#3]
Hello, this php ocr script uses file bootstrap.php, as it can be seen in example. But there is no such file in package...so it does not work

**Comment by bpteam** [comment]
Hello, mav1. Thanks for interesting on this project. Can you provide code snippet of example where bootstrab.php is writen?
I look at /example.php and see vendor/autoload.php
Feel free for ask any questions.

**Comment by mav1** [comment]
Hello, sorry, bootstrap.php was included in another example (not from github.com), but there is also no "vendor/autoload.php" (that is included in /example.php) =)

**Comment by bpteam** [comment]
You should use composer for generate vendor autoload. Look at here https://getcomposer.org/
